logging:
  level:
    root: INFO
    lt.cv: DEBUG

spring:
  jackson:
    defaultPropertyInclusion: non-null
  datasource:
    url: jdbc:h2:mem:mydb
    username: cv_admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true